### ISSUE TITLE
Need a JAVA Entity class for Spring Boot

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/SmartFlatRegistration-Hacktoberfest22#1]
Entity Class needed with Spring Boot Initializer Structure including pom.xml Must be a maven project.
Anyone have this please give me asap.

**Comment by mriganka56** [comment]
Yes, Can I do it, please?

**Comment by arpanghosh2416** [comment]
Okay Sure. @mriganka56

**Comment by arpanghosh2416** [comment]
Thank You @mriganka56
