### ISSUE TITLE
Java Backend Architecture Needed

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/SmartFlatRegistration-Hacktoberfest22#3]
Proper Architecture Needed: - 

1. Need a Entity Repository Architecture
2. Need a Service Repository Architecture
3. Need a Controller Architecture for REST API
4. Need a JPA Repository

**Comment by mriganka56** [comment]
I would love to contribute to the Exception Classes....quite familiar with them.

**Comment by arpanghosh2416** [comment]
Ok mriganka56.

**Comment by mriganka56** [comment]
I would like to contribute.......quite familiar with the topic @arpanghosh2416

**Comment by mriganka56** [comment]
You can assign me

**Comment by arpanghosh2416** [comment]
@mriganka56 Ok I am assigning it to you then

**Comment by arpanghosh2416** [comment]
@mriganka56 Thank You for your help.
